name: Test Github Script Output

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "current tag: The tag for this release"
        required: true
        default: v0.1.0-rc.2
      prev_tag:
        description: "previous tag: Tag from which to start calculating the changelog"
        required: true
        default: v0.1.0-beta.0
      commit_ref:
        description: "commit ref: The branch, tag or SHA of the commit to use for the release."
        required: false
        default: main

defaults:
  run:
    shell: bash

jobs:
  image_build:
    name: Image build
    runs-on: ubuntu-latest
    steps:
      - id: get_channel
        uses: actions/github-script@v6
        with:
          script: |
            const version = '${{ github.event.inputs.tag }}';
            return /^v\d+\.\d+\.\d+-\w+/.test(version) ? 'prerelease' : 'stable';
      - name: build the operator bundle and container images and push the images to quay
        run: |
          VERSION='${{ github.event.inputs.tag }}' CHANNELS='${{ steps.get_channel.outputs.result }}' DEFAULT_CHANNEL='stable' echo 'hello!'
